"""Minimal persistence ports required by the Phase 1 foundation."""

from typing import Protocol

from warehouse_control_center.domain.entities import AuditEvent, Courier, Shipment, User


class UserRepository(Protocol):
    def add(self, user: User) -> User: ...

    def save(self, user: User) -> User: ...

    def get_by_id(self, user_id: int) -> User | None: ...

    def get_by_normalized_username(self, username: str) -> User | None: ...

    def list_users(
        self,
        *,
        search: str | None = None,
        include_archived: bool = False,
    ) -> list[User]: ...

    def count_users(self) -> int: ...

    def count_active_admins(self) -> int: ...

    def lock_for_administration(self) -> None: ...


class CourierRepository(Protocol):
    def add(self, courier: Courier) -> Courier: ...

    def get_by_id(self, courier_id: int) -> Courier | None: ...

    def get_by_normalized_code(self, courier_code: str) -> Courier | None: ...


class ShipmentRepository(Protocol):
    def add(self, shipment: Shipment) -> Shipment: ...

    def get_by_id(self, shipment_id: int) -> Shipment | None: ...

    def get_by_normalized_tracking_number(self, tracking_number: str) -> Shipment | None: ...

    def get_by_normalized_barcode(self, barcode: str) -> Shipment | None: ...


class AuditRepository(Protocol):
    """Append-only audit persistence; update and delete are intentionally absent."""

    def add(self, event: AuditEvent) -> AuditEvent: ...

    def get_by_id(self, event_id: int) -> AuditEvent | None: ...
