"""Centralized values shared by all application layers."""

from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    WAREHOUSE_OPERATOR = "WAREHOUSE_OPERATOR"
    SUPERVISOR = "SUPERVISOR"


class ShipmentStatus(StrEnum):
    RECEIVED = "RECEIVED"
    SORTING = "SORTING"
    READY_FOR_COURIER = "READY_FOR_COURIER"
    ASSIGNED = "ASSIGNED"
    DISPATCHED = "DISPATCHED"
    RETURNED = "RETURNED"
    PROBLEM = "PROBLEM"


class ProblemType(StrEnum):
    DAMAGED = "DAMAGED"
    WRONG_ADDRESS = "WRONG_ADDRESS"
    MISSING_DATA = "MISSING_DATA"
    NOT_FOUND = "NOT_FOUND"
    OTHER = "OTHER"


class Permission(StrEnum):
    VIEW_SHIPMENTS = "VIEW_SHIPMENTS"
    CREATE_SHIPMENT = "CREATE_SHIPMENT"
    EDIT_SHIPMENT = "EDIT_SHIPMENT"
    CHANGE_SHIPMENT_STATUS = "CHANGE_SHIPMENT_STATUS"
    ASSIGN_SHIPMENT = "ASSIGN_SHIPMENT"
    MARK_PROBLEM = "MARK_PROBLEM"
    RESOLVE_PROBLEM = "RESOLVE_PROBLEM"
    OVERRIDE_STATUS_TRANSITION = "OVERRIDE_STATUS_TRANSITION"
    ARCHIVE_SHIPMENT = "ARCHIVE_SHIPMENT"
    RESTORE_SHIPMENT = "RESTORE_SHIPMENT"
    VIEW_DASHBOARD = "VIEW_DASHBOARD"
    VIEW_REPORTS = "VIEW_REPORTS"
    EXPORT_REPORTS = "EXPORT_REPORTS"
    IMPORT_SHIPMENTS = "IMPORT_SHIPMENTS"
    VIEW_COURIERS = "VIEW_COURIERS"
    MANAGE_COURIERS = "MANAGE_COURIERS"
    VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG"
    MANAGE_USERS = "MANAGE_USERS"
    MANAGE_SETTINGS = "MANAGE_SETTINGS"
    CREATE_BACKUP = "CREATE_BACKUP"


class AuditAction(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGIN_BLOCKED = "LOGIN_BLOCKED"
    LOGOUT = "LOGOUT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"
    USER_CREATED = "USER_CREATED"
    USER_RENAMED = "USER_RENAMED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_ARCHIVED = "USER_ARCHIVED"
    USER_RESTORED = "USER_RESTORED"
    FIRST_ADMIN_CREATED = "FIRST_ADMIN_CREATED"
